site_name: Unitful.jl
site_description: Unitful.jl for units in Julia

repo_url: https://github.com/ajkeller34/Unitful.jl/

pages:
- Home: 'index.md'
- Design and implementation: 'implementation.md'
- Miscellaneous:
    - 'Release notes': 'releases.md'
    - 'License': 'LICENSE.md'
